<OBJECT CODEWORD-CHANCERY
    (DESC "Chancery")
    (SYNONYM CHANCERY)>

<OBJECT CODEWORD-DETRUDE
    (DESC "Detrude")
    (SYNONYM DETRUDE)>

<OBJECT CODEWORD-MARATHON
    (DESC "Marathon")
    (SYNONYM MARATHON)>

<OBJECT CODEWORD-PROSPERO
    (DESC "Prospero")
    (SYNONYM PROSPERO)>
