"Down Among the Dead Men (ZIL)"

<CONSTANT GAME-TITLE "||Down Among the Dead Men">
<CONSTANT GAME-DESCRIPTION "|Dave Morris (1993)||Implemented in ZIL by SD Separa (2020)|">
<CONSTANT RELEASEID 6>
<CONSTANT IFID "A9F9AFD0-0DE1-44FD-AD19-78E02A4A535F">
<VERSION XZIP>

<INSERT-FILE "minilib">
<INSERT-FILE "story">

<ROUTINE GO ()
    <V-VERSION>
    <TELL CR "IFID: ">
    <TELL IFID>
    <CRLF>
    <GAME-BOOK>
    <QUIT-MSG>>
